# Change these first
owner: shakthineetacademy # Your GitHub organization or username, where this repository lives
repo: sna-wise-path-dev-uptime # The name of this repository

sites:
  - name: SNA Dev Sign-In page
    url: $SNA_DEV_SIGN_IN_PAGE
  - name: SNA Prod Sign-In page
    url: $SNA_PROD_SIGN_IN_PAGE
  - name: Dev Portal Sign-In
    url: $DEV_PORTAL
  - name: SNA Prod portal Sign-In
    url: $SNA_PROD_PORTAL
  - name: Dev login
    url: $SNA_DEV_SIGN_IN_PAGE
    method: POST
    headers:
    - "Content-Type: application/json"
    body: $DEV_LOGIN
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org # Using github instead
  baseUrl: /sna-wise-path-dev-uptime
  # todo: change to company or SNA logo
  logoUrl: https://raw.githubusercontent.com/shakthineetacademy/sna-wise-path-dev-uptime/master/assets/upptime-icon.svg
  # favicon: https://example.com/favicon.png
  # faviconSvg: https://example.com/logo.svg
  name: SNA uptime portal
  introTitle: "**SNA** Status Page"
  introMessage: You are looking at the status page of **wiseath's SNA lms** portal.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
